"""Build tools/solve_copper6.py from route_2026-09-16/tools/solve_copper.py (patched copy; the original is untouched).

Changes:
- LAYERS comes from the copper export (6 or 8 layers).
- STACKS gains 'L8' (the board file's 8-layer stackup) and every JLC 6-layer stackup in stackups.py.
- The over-plane height is per cell: the vertical distance to the nearest layer that has GND copper at that cell
  (instead of a fixed height per layer to In1/In6). Layers with no GND anywhere in the column use H_NONE.
- --dump DIR saves, for each solved branch, the per-layer sheet currents (A/mm at 1 A) and the grid, so the loop
  inductance can be recomputed for any stackup without re-solving (the DC current split does not depend on it).
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(HERE, '..', '..', 'route_2026-09-16', 'tools', 'solve_copper.py'), encoding='utf-8').read()


def sub(old, new, count=1):
    global src
    assert src.count(old) == count, (old[:60], src.count(old))
    src = src.replace(old, new)


# stacks
sub("LAYERS = ['F.Cu', 'In1.Cu', 'In2.Cu', 'In3.Cu', 'In4.Cu', 'In5.Cu', 'In6.Cu', 'B.Cu']\n",
    "LAYERS = ['F.Cu', 'In1.Cu', 'In2.Cu', 'In3.Cu', 'In4.Cu', 'In5.Cu', 'In6.Cu', 'B.Cu']\n"
    "sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))\n"
    "from stackups import STACKS as _JLC6\n"
    "STACKS['L8'] = dict(cu=[0.035] + [0.030] * 6 + [0.035], gaps=[0.109, 0.25, 0.218, 0.25, 0.218, 0.25, 0.109])\n"
    "for _k, _g in _JLC6.items():\n"
    "    STACKS[_k] = dict(cu=[0.035] + [0.030] * 4 + [0.035], gaps=list(_g))\n"
    "H_NONE = 1.6\n"
    "DUMP = None\n")
# per-cell height to the nearest GND copper, replacing the fixed HPLANE table
sub("""    HPLANE = {'B': {'F.Cu': 0.109, 'In2.Cu': 0.25, 'In3.Cu': 0.498, 'In5.Cu': 0.25, 'B.Cu': 0.109},
              'C': {'F.Cu': 0.203, 'In2.Cu': 0.2, 'In3.Cu': 0.368, 'In5.Cu': 0.2, 'B.Cu': 0.203}}[stack]
""", """    gcu = cop['nets'].get('GND', {})
    gmask = {ln: raster(gcu[ln], x0, y0, nx, ny, h) if ln in gcu else np.zeros((ny, nx), bool) for ln in LAYERS}
    HMAP = {}
    for ln in layers:
        hm = np.full((ny, nx), np.inf)
        for k in LAYERS:
            if k != ln:
                hm = np.where(gmask[k], np.minimum(hm, abs(z[k] - z[ln])), hm)
        HMAP[ln] = np.where(np.isfinite(hm), hm, H_NONE)
    dump = {}
""")
sub("""        if ln in HPLANE:
            sx_ = np.where(ok, SIGMA * cu[ln] * gx * s, 0.0)      # sheet current, A/mm
            sy_ = np.where(ok, SIGMA * cu[ln] * gy * s, 0.0)
            jx_tot += sx_
            jy_tot += sy_
            mag = np.hypot(sx_, sy_)
            j_abs += mag
            jh += mag * HPLANE[ln]
""", """        if net != 'GND':
            sx_ = np.where(ok, SIGMA * cu[ln] * gx * s, 0.0)      # sheet current, A/mm
            sy_ = np.where(ok, SIGMA * cu[ln] * gy * s, 0.0)
            jx_tot += sx_
            jy_tot += sy_
            mag = np.hypot(sx_, sy_)
            j_abs += mag
            jh += mag * HMAP[ln]
            dump[ln] = (sx_ / br['I'], sy_ / br['I'])
""")
sub("""    res['L_overplane_nH'] = float(MU0 * (heff * (jx_tot ** 2 + jy_tot ** 2)).sum() * h * h / br['I'] ** 2 * 1e9)
""", """    res['L_overplane_nH'] = float(MU0 * (heff * (jx_tot ** 2 + jy_tot ** 2)).sum() * h * h / br['I'] ** 2 * 1e9)
    if DUMP and dump:
        safe = ''.join(ch if ch.isalnum() or ch in '_-' else '_' for ch in br['name'])
        arrs = {}
        for ln, (ax, ay) in dump.items():
            arrs['sx_' + ln] = ax.astype(np.float32)
            arrs['sy_' + ln] = ay.astype(np.float32)
        np.savez_compressed(os.path.join(DUMP, safe + '.npz'), x0=x0, y0=y0, h=h, nx=nx, ny=ny,
                            layers=np.array(list(dump)), **arrs)
""")
# LAYERS from the export, in the worker and in main; --dump
sub("""def _init(path):
    global _COP
    _COP = json.load(open(path))
""", """def _init(path, dump=None):
    global _COP, DUMP
    _COP = json.load(open(path))
    LAYERS[:] = _COP['layers']
    DUMP = dump
""")
sub("""    a = sys.argv[1:]
    branches = json.load(open(a[1]))
""", """    a = sys.argv[1:]
    branches = json.load(open(a[1]))
    global DUMP
    LAYERS[:] = json.load(open(a[0]))['layers']
    DUMP = a[a.index('--dump') + 1] if '--dump' in a else None
    if DUMP:
        os.makedirs(DUMP, exist_ok=True)
""")
sub("initializer=_init, initargs=(a[0],)", "initializer=_init, initargs=(a[0], DUMP)")
open(os.path.join(HERE, 'solve_copper6.py'), 'w', encoding='utf-8').write(
    '# GENERATED by make_solver6.py from route_2026-09-16/tools/solve_copper.py - edit the generator, not this file.\n'
    + src)
print('wrote solve_copper6.py')
