"""DC conduction solve of power branches on exported copper (system Python: numpy, scipy, matplotlib).

usage: python solve_copper.py COPPER.json BRANCHES.json --stack B|C [--only NAME,NAME] [--out REPORT.json]
                              [--png DIR]

Method (after AUDIT_RESPONSE.md section 1): each net's copper is rasterised per layer on a square grid; cells
join their 4 neighbours with sheet conductance sigma*t; plated barrels (vias 20 um; THT pins treated as filled)
join the layers; the branch's source pads are held at 1 V and its sink pads at 0 V. The neck is found by the
co-area formula: for each equipotential band, per-layer cross-section = integral |grad phi| dA / dphi, scaled
so the band carries the whole branch current; IPC-2221 rise is evaluated per layer at every band and the
worst band is reported. Via barrels report their largest segment current against the IPC 10 C rating.
"""
import json, math, sys, os
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
from scipy.sparse.csgraph import connected_components
from matplotlib.path import Path

SIGMA = 1.0 / 1.72e-5            # S/mm (copper, 20 C)
T_PLATE = 0.020                  # mm barrel plating
STACKS = {  # JLCPCB 8L 1.6 mm, no impedance requirement (gsuberland/jlcpcb_autogenerated_stackups)
    'B': dict(cu=[0.035, 0.030, 0.030, 0.030, 0.030, 0.030, 0.030, 0.035],
              gaps=[0.109, 0.25, 0.218, 0.25, 0.218, 0.25, 0.109]),
    'C': dict(cu=[0.070, 0.030, 0.030, 0.030, 0.030, 0.030, 0.030, 0.070],
              gaps=[0.203, 0.2, 0.138, 0.2, 0.138, 0.2, 0.203]),
}
LAYERS = ['F.Cu', 'In1.Cu', 'In2.Cu', 'In3.Cu', 'In4.Cu', 'In5.Cu', 'In6.Cu', 'B.Cu']
OUTER = {'F.Cu', 'B.Cu'}


def via_rating(drill):
    pts = [(0.25, 0.71), (0.30, 0.80), (0.40, 0.97)]
    if drill <= 0.25:
        return 0.71
    for (d0, r0), (d1, r1) in zip(pts, pts[1:]):
        if drill <= d1:
            return r0 + (r1 - r0) * (drill - d0) / (d1 - d0)
    return 0.97 * (drill / 0.40) ** 0.725          # IPC-2221: current scales with barrel area^0.725


def ipc_rise(I, area_mm2, outer):
    if area_mm2 <= 0:
        return float('inf')
    k = 0.048 if outer else 0.024
    a = area_mm2 * 1550.0031
    return (abs(I) / (k * a ** 0.725)) ** (1 / 0.44)


def raster(polys, x0, y0, nx, ny, h):
    """Boolean mask of cell centres inside the union of polygons (dict {'hole': pts} subtracts)."""
    m = np.zeros((ny, nx), bool)
    for poly in polys:
        hole = isinstance(poly, dict)
        pts = np.asarray(poly['hole'] if hole else poly)
        if len(pts) < 3:
            continue
        i0 = max(int(math.floor((pts[:, 0].min() - x0) / h)), 0)
        i1 = min(int(math.ceil((pts[:, 0].max() - x0) / h)) + 1, nx)
        j0 = max(int(math.floor((pts[:, 1].min() - y0) / h)), 0)
        j1 = min(int(math.ceil((pts[:, 1].max() - y0) / h)) + 1, ny)
        if i1 <= i0 or j1 <= j0:
            continue
        xs = x0 + (np.arange(i0, i1) + 0.5) * h
        ys = y0 + (np.arange(j0, j1) + 0.5) * h
        X, Y = np.meshgrid(xs, ys)
        inside = Path(pts).contains_points(np.c_[X.ravel(), Y.ravel()]).reshape(X.shape)
        if hole:
            m[j0:j1, i0:i1] &= ~inside
        else:
            m[j0:j1, i0:i1] |= inside
    return m


def solve_branch(cop, br, stack, png_dir=None):
    net = br['net']
    h = br.get('grid', 0.1)
    st = STACKS[stack]
    cu = dict(zip(LAYERS, st['cu']))
    z = {}
    acc = 0.0
    for i, ln in enumerate(LAYERS):
        z[ln] = acc + st['cu'][i] / 2
        acc += st['cu'][i] + (st['gaps'][i] if i < len(st['gaps']) else 0)
    netcu = cop['nets'].get(net, {})
    allpts = np.array([p for ln in netcu for poly in netcu[ln] if not isinstance(poly, dict) for p in poly])
    x0, y0 = allpts[:, 0].min() - 2 * h, allpts[:, 1].min() - 2 * h
    nx = int(math.ceil((allpts[:, 0].max() - x0) / h)) + 3
    ny = int(math.ceil((allpts[:, 1].max() - y0) / h)) + 3
    layers = [ln for ln in LAYERS if ln in netcu]
    masks = {ln: raster(netcu[ln], x0, y0, nx, ny, h) for ln in layers}
    # node numbering
    offs, ids, n = {}, {}, 0
    for ln in layers:
        idx = -np.ones((ny, nx), np.int64)
        cnt = int(masks[ln].sum())
        idx[masks[ln]] = np.arange(n, n + cnt)
        ids[ln] = idx
        n += cnt
    rows, cols, vals = [], [], []

    def link(a, b, g):
        rows.append(a); cols.append(b); vals.append(g)

    for ln in layers:
        idx = ids[ln]
        g = SIGMA * cu[ln]
        for (A, B) in ((idx[:, :-1], idx[:, 1:]), (idx[:-1, :], idx[1:, :])):
            ok = (A >= 0) & (B >= 0)
            link(A[ok], B[ok], np.full(int(ok.sum()), g))
    # terminals
    padmap = {}
    for p in cop['pads']:
        padmap.setdefault((p['ref'], p['num']), []).append(p)
    fixed = {}
    for key, volt in (('src', 1.0), ('snk', 0.0)):
        for ref, num in br[key]:
            plist = padmap.get((ref, str(num)))
            if not plist:
                raise SystemExit('%s: pad %s.%s not found' % (br['name'], ref, num))
            for p in plist:
                for ln, polys in p['polys'].items():
                    if ln not in masks:
                        continue
                    pm = raster(polys, x0, y0, nx, ny, h) & masks[ln]
                    if not pm.any():   # tiny pad: take the centre cell
                        i, j = int((p['x'] - x0) / h), int((p['y'] - y0) / h)
                        if 0 <= i < nx and 0 <= j < ny and masks[ln][j, i]:
                            pm[j, i] = True
                    for node in ids[ln][pm]:
                        fixed[int(node)] = volt
    # barrels
    barrels = []
    nb_extra = 0
    for b in cop['barrels']:
        if b['net'] != net:
            continue
        i, j = int((b['x'] - x0) / h), int((b['y'] - y0) / h)
        r = b['drill'] / 2 + 0.75 * h
        rad = int(math.ceil(r / h)) + 1
        attach = {}
        for ln in b['layers']:
            if ln not in masks:
                continue
            cells = []
            for dj in range(-rad, rad + 1):
                for di in range(-rad, rad + 1):
                    ii, jj = i + di, j + dj
                    if 0 <= ii < nx and 0 <= jj < ny and ids[ln][jj, ii] >= 0:
                        cx, cy = x0 + (ii + 0.5) * h, y0 + (jj + 0.5) * h
                        if math.hypot(cx - b['x'], cy - b['y']) <= r:
                            cells.append(int(ids[ln][jj, ii]))
            if cells:
                attach[ln] = cells
        if len(attach) < 2:
            continue
        lns = [ln for ln in LAYERS if ln in attach]
        nodes = {}
        for ln in lns:
            nodes[ln] = n + nb_extra
            nb_extra += 1
            for c in attach[ln]:
                link(np.array([nodes[ln]]), np.array([c]), np.array([1e4]))
        segs = []
        for la, lb in zip(lns, lns[1:]):
            dz = abs(z[lb] - z[la])
            d = b['drill']
            g = SIGMA * math.pi * (d - T_PLATE) * T_PLATE / dz
            if b['kind'] == 'tht':
                g *= 20.0          # soldered pin in the hole
            link(np.array([nodes[la]]), np.array([nodes[lb]]), np.array([g]))
            segs.append((nodes[la], nodes[lb], g, la, lb))
        barrels.append(dict(b=b, segs=segs))
    N = n + nb_extra
    r_ = np.concatenate([np.atleast_1d(a) for a in rows])
    c_ = np.concatenate([np.atleast_1d(a) for a in cols])
    v_ = np.concatenate([np.atleast_1d(a) for a in vals])
    G = sp.coo_matrix((v_, (r_, c_)), shape=(N, N)).tocsr()
    G = G + G.T
    L = sp.diags(np.asarray(G.sum(axis=1)).ravel()) - G
    # keep only components touching both terminal sets
    ncomp, lab = connected_components(G, directed=False)
    fx = np.array(sorted(fixed))
    fv = np.array([fixed[k] for k in fx])
    comp_src = set(lab[fx[fv > 0.5]])
    comp_snk = set(lab[fx[fv < 0.5]])
    live = np.isin(lab, list(comp_src & comp_snk))
    if not live.any():
        return dict(name=br['name'], net=net, error='source and sink not connected')
    V = np.full(N, np.nan)
    isfix = np.zeros(N, bool)
    isfix[fx] = True
    V[fx] = fv
    free = np.where(live & ~isfix)[0]
    fixl = np.where(live & isfix)[0]
    Lff = L[free][:, free].tocsc()
    rhs = -L[free][:, fixl] @ V[fixl]
    V[free] = spla.spsolve(Lff, rhs, permc_spec='MMD_AT_PLUS_A')
    Vz = np.where(np.isnan(V), 0.0, V)
    inj = L @ Vz
    src_nodes = fx[fv > 0.5]
    I0 = float(inj[src_nodes][live[src_nodes]].sum())
    s = br['I'] / I0
    R = 1.0 / I0
    res = dict(name=br['name'], net=net, I=br['I'], R_mohm=R * 1e3, dV_mV=br['I'] * R * 1e3, P_W=br['I'] ** 2 * R,
               grid=h, cells=int(n), barrels=len(barrels))
    # co-area neck analysis
    NB = 400
    edges_ = np.linspace(0, 1, NB + 1)
    P = np.zeros((NB, len(layers)))
    Agr = np.zeros((NB, len(layers)))
    Cx = np.zeros((NB, len(layers)))
    Cy = np.zeros((NB, len(layers)))
    jmax = {}
    nsq = {}
    HPLANE = {'B': {'F.Cu': 0.109, 'In2.Cu': 0.25, 'In3.Cu': 0.498, 'In5.Cu': 0.25, 'B.Cu': 0.109},
              'C': {'F.Cu': 0.203, 'In2.Cu': 0.2, 'In3.Cu': 0.368, 'In5.Cu': 0.2, 'B.Cu': 0.203}}[stack]
    jx_tot = np.zeros((ny, nx))
    jy_tot = np.zeros((ny, nx))
    j_abs = np.zeros((ny, nx))
    jh = np.zeros((ny, nx))
    for li, ln in enumerate(layers):
        idx = ids[ln]
        phi = np.full((ny, nx), np.nan)
        m = idx >= 0
        phi[m] = V[idx[m]]
        gx = np.full((ny, nx), np.nan)
        gy = np.full((ny, nx), np.nan)
        c = (phi[:, 2:] - phi[:, :-2]) / (2 * h)
        gx[:, 1:-1] = c
        f = (phi[:, 1:] - phi[:, :-1]) / h
        gx = np.where(np.isnan(gx), np.pad(f, ((0, 0), (0, 1)), constant_values=np.nan), gx)
        gx = np.where(np.isnan(gx), np.pad(f, ((0, 0), (1, 0)), constant_values=np.nan), gx)
        c = (phi[2:, :] - phi[:-2, :]) / (2 * h)
        gy[1:-1, :] = c
        f = (phi[1:, :] - phi[:-1, :]) / h
        gy = np.where(np.isnan(gy), np.pad(f, ((0, 1), (0, 0)), constant_values=np.nan), gy)
        gy = np.where(np.isnan(gy), np.pad(f, ((1, 0), (0, 0)), constant_values=np.nan), gy)
        gx = np.nan_to_num(gx)
        gy = np.nan_to_num(gy)
        gm = np.hypot(gx, gy)
        ok = m & ~np.isnan(phi)
        ok[m] &= ~isfix[idx[m]]
        J = SIGMA * gm * s                     # A/mm2
        nsq[ln] = float(((SIGMA * cu[ln] * gm[ok] * s) ** 2).sum() * h * h / br['I'] ** 2)   # effective squares
        if ln in HPLANE:
            sx_ = np.where(ok, SIGMA * cu[ln] * gx * s, 0.0)      # sheet current, A/mm
            sy_ = np.where(ok, SIGMA * cu[ln] * gy * s, 0.0)
            jx_tot += sx_
            jy_tot += sy_
            mag = np.hypot(sx_, sy_)
            j_abs += mag
            jh += mag * HPLANE[ln]
        if ok.any():
            k = np.argmax(np.where(ok, J, -1))
            jj, ii = divmod(int(k), nx)
            jmax[ln] = (float(J[jj, ii]), x0 + (ii + 0.5) * h, y0 + (jj + 0.5) * h)
        b = np.clip((phi[ok] * NB).astype(int), 0, NB - 1)
        w = gm[ok] * h * h
        np.add.at(Agr[:, li], b, w)
        pw = SIGMA * cu[ln] * gm[ok] ** 2 * h * h
        np.add.at(P[:, li], b, pw)
        jj, ii = np.nonzero(ok)
        np.add.at(Cx[:, li], b, pw * (x0 + (ii + 0.5) * h))
        np.add.at(Cy[:, li], b, pw * (y0 + (jj + 0.5) * h))
    Pb = np.zeros(NB)
    Ab = np.zeros(NB)
    vias = []
    for bb in barrels:
        worst = 0.0
        for na, nbn, g, la, lb in bb['segs']:
            va, vb = Vz[na], Vz[nbn]
            i_seg = g * abs(va - vb) * s
            worst = max(worst, i_seg)
            lo, hi = sorted((va, vb))
            if hi - lo > 1e-12:
                for k in range(max(int(lo * NB), 0), min(int(hi * NB) + 1, NB)):
                    ov = max(0.0, min(hi, edges_[k + 1]) - max(lo, edges_[k]))
                    Pb[k] += g * abs(va - vb) * ov          # current (at 1 V) times band overlap
                    Ab[k] += math.pi * (bb['b']['drill'] - T_PLATE) * T_PLATE * ov / (1.0 / NB)
        if bb['b']['kind'] == 'via':
            rating = via_rating(bb['b']['drill'])
            vias.append(dict(x=bb['b']['x'], y=bb['b']['y'], drill=bb['b']['drill'], I=worst, ratio=worst / rating))
    # sliding window over bands (5 bands = 1.25 % of the potential) to steady the per-band estimates
    kern = np.ones(5)
    P = np.stack([np.convolve(P[:, i], kern, 'same') for i in range(P.shape[1])], axis=1)
    Agr = np.stack([np.convolve(Agr[:, i], kern, 'same') for i in range(Agr.shape[1])], axis=1)
    Cx = np.stack([np.convolve(Cx[:, i], kern, 'same') for i in range(Cx.shape[1])], axis=1)
    Cy = np.stack([np.convolve(Cy[:, i], kern, 'same') for i in range(Cy.shape[1])], axis=1)
    Pb = np.convolve(Pb, kern, 'same')
    tot = P.sum(axis=1) + Pb
    worst = dict(rise=0.0)
    minsec = dict(area=float('inf'))
    band_rise = np.zeros(NB)
    band_len = np.zeros(NB)
    for k in range(NB):
        if tot[k] <= 0.02 * np.median(tot[tot > 0]) if (tot > 0).any() else True:
            continue
        rises, area = [], 0.0
        for li, ln in enumerate(layers):
            if P[k, li] <= 0:
                continue
            share = P[k, li] / tot[k]
            width = Agr[k, li] * I0 / tot[k]
            a = width * cu[ln]
            area += a
            rises.append((ipc_rise(br['I'] * share, a, ln in OUTER), ln, width, share,
                          Cx[k, li] / P[k, li], Cy[k, li] / P[k, li]))
        area += Ab[k] * (Pb[k] / tot[k] if tot[k] else 0) * 0 + 0.0
        if rises:
            r0 = max(rises)
            band_rise[k] = r0[0]
            li0 = layers.index(r0[1])
            if Agr[k, li0] > 0:
                e_mean = P[k, li0] / Agr[k, li0] / (SIGMA * cu[r0[1]])        # V/mm, current-weighted
                band_len[k] = (1.0 / NB) / e_mean if e_mean > 0 else 0.0
            if r0[0] > worst['rise']:
                worst = dict(rise=r0[0], layer=r0[1], width=r0[2], share=r0[3], x=r0[4], y=r0[5], phi=k / NB)
            if area < minsec['area']:
                minsec = dict(area=area, phi=k / NB, x=r0[4], y=r0[5])
    if worst['rise'] > 0:
        # length along the flow over which the rise stays above half the worst value (contiguous bands)
        k0 = int(worst['phi'] * NB)
        lo = k0
        while lo > 0 and band_rise[lo - 1] >= 0.5 * worst['rise']:
            lo -= 1
        hi = k0
        while hi < NB - 1 and band_rise[hi + 1] >= 0.5 * worst['rise']:
            hi += 1
        worst['length'] = float(band_len[lo:hi + 1].sum())
    # worst rise among necks at least LONG mm long (contiguous bands above half that band's rise)
    LONG = 2.0
    worst_long = dict(rise=0.0)
    for k in np.argsort(-band_rise):
        if band_rise[k] <= worst_long['rise'] or band_rise[k] <= 0:
            break
        lo = hi = int(k)
        while lo > 0 and band_rise[lo - 1] >= 0.5 * band_rise[k]:
            lo -= 1
        while hi < NB - 1 and band_rise[hi + 1] >= 0.5 * band_rise[k]:
            hi += 1
        ln_ = float(band_len[lo:hi + 1].sum())
        if ln_ >= LONG:
            worst_long = dict(rise=float(band_rise[k]), length=ln_, phi=int(k) / NB)
            break
    res['neck_long'] = worst_long
    res['neck'] = worst
    res['min_section_mm2'] = minsec
    res['jmax'] = jmax
    res['nsq'] = nsq
    # coupled over-plane inductance: layers stacked over one footprint share their flux, so sum the sheet
    # currents first and weight by the current-weighted height to the nearest GND plane
    heff = np.where(j_abs > 0, jh / np.maximum(j_abs, 1e-30), 0.0)
    MU0 = 4e-7 * math.pi * 1e-3
    res['L_overplane_nH'] = float(MU0 * (heff * (jx_tot ** 2 + jy_tot ** 2)).sum() * h * h / br['I'] ** 2 * 1e9)
    vias.sort(key=lambda v: -v['ratio'])
    res['vias_used'] = sum(1 for v in vias if v['I'] > 0.01 * br['I'])
    res['vias_over'] = sum(1 for v in vias if v['ratio'] > 1.0)
    res['worst_vias'] = vias[:5]
    res['single_via'] = [v for v in vias if v['I'] >= 0.95 * br['I']]
    if png_dir:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
        fig, axs = plt.subplots(1, len(layers), figsize=(4.2 * len(layers), 5))
        axs = np.atleast_1d(axs)
        for ax, ln in zip(axs, layers):
            idx = ids[ln]
            phi = np.full((ny, nx), np.nan)
            m = idx >= 0
            phi[m] = V[idx[m]]
            gx = np.zeros_like(phi)
            gy = np.zeros_like(phi)
            ok2 = m[:, 1:] & m[:, :-1]
            dx = np.where(ok2, (np.nan_to_num(phi[:, 1:]) - np.nan_to_num(phi[:, :-1])) / h, 0.0)
            gx[:, 1:] += dx
            gx[:, :-1] += dx
            ok2 = m[1:, :] & m[:-1, :]
            dy = np.where(ok2, (np.nan_to_num(phi[1:, :]) - np.nan_to_num(phi[:-1, :])) / h, 0.0)
            gy[1:, :] += dy
            gy[:-1, :] += dy
            J = np.where(m, SIGMA * np.hypot(gx, gy) / 2 * s, np.nan)
            im = ax.imshow(J, extent=[x0, x0 + nx * h, y0 + ny * h, y0], cmap='inferno',
                           vmax=np.nanpercentile(J, 99.5) if np.isfinite(J).any() else 1)
            ax.set_title('%s %s (A/mm2)' % (br['name'], ln), fontsize=8)
            plt.colorbar(im, ax=ax, fraction=0.04)
        fig.tight_layout()
        fig.savefig(os.path.join(png_dir, '%s_%s.png' % (''.join(ch if ch.isalnum() or ch in '_-' else '_' for ch in br['name']), stack)), dpi=90)
        plt.close(fig)
    return res


_COP = None


def _init(path):
    global _COP
    _COP = json.load(open(path))


def _solve(args):
    br, stack, png = args
    return solve_branch(_COP, br, stack, png)


def main():
    a = sys.argv[1:]
    branches = json.load(open(a[1]))
    stack = a[a.index('--stack') + 1] if '--stack' in a else 'B'
    only = a[a.index('--only') + 1].split(',') if '--only' in a else None
    out = a[a.index('--out') + 1] if '--out' in a else None
    png = a[a.index('--png') + 1] if '--png' in a else None
    if png:
        os.makedirs(png, exist_ok=True)
    todo = [br for br in branches if not only or br['name'] in only]
    from concurrent.futures import ProcessPoolExecutor
    small = [br for br in todo if br['net'] != 'GND']
    large = [br for br in todo if br['net'] == 'GND']
    done = {}
    for group, workers in ((small, 8), (large, 2)):
        if not group:
            continue
        with ProcessPoolExecutor(max_workers=min(len(group), workers), initializer=_init, initargs=(a[0],)) as ex:
            for br, r in zip(group, ex.map(_solve, [(br, stack, png) for br in group])):
                done[br['name']] = r
    results = [done[br['name']] for br in todo]
    for r in results:
        if 'error' in r:
            print('%-28s ERROR %s' % (r['name'], r['error']))
            continue
        nk = r['neck']
        wv = r['worst_vias'][0] if r['worst_vias'] else None
        print('%-28s %5.2f A  R %7.3f mOhm  %6.2f mV  %5.2f W | neck %6.1f C on %-6s w %5.2f mm share %3.0f%% at '
              '(%.1f, %.1f) len %.1f | long-neck %5.1f C | vias used %d, over %d, worst %s'
              % (r['name'], r['I'], r['R_mohm'], r['dV_mV'], r['P_W'], nk.get('rise', 0), nk.get('layer', '-'),
                 nk.get('width', 0), 100 * nk.get('share', 0), nk.get('x', 0), nk.get('y', 0), nk.get('length', 0),
                 r['neck_long'].get('rise', 0),
                 r['vias_used'],
                 r['vias_over'], ('%.2f A %.2fx at (%.1f, %.1f)' % (wv['I'], wv['ratio'], wv['x'], wv['y'])) if wv else '-'))
    if out:
        json.dump(results, open(out, 'w'), indent=1)


if __name__ == '__main__':
    main()
