"""Write the JLCPCB 8-layer 1.6 mm stackup, 1 oz outer / 1 oz inner (option B, user decision 2026-09-16), into a
.kicad_pcb file's setup section (text edit; KiCad's Python does not wrap BOARD_STACKUP).

usage: python set_stackup.py BOARD.kicad_pcb
Source: jlcpcb_8L_1.6mm_outer1oz_inner1oz_NOREQ (gsuberland/jlcpcb_autogenerated_stackups, Nan Ya NP-155F):
Cu 0.035 | 2116 0.109 | Cu 0.030 | core 0.25 | Cu 0.030 | 2116+2116 0.218 | Cu 0.030 | core 0.25 | Cu 0.030 |
2116+2116 0.218 | Cu 0.030 | core 0.25 | Cu 0.030 | 2116 0.109 | Cu 0.035  = 1.654 mm copper + dielectric.
Copper finish is not decided, so it is written as "None".
"""
import re, sys

path = sys.argv[1]
s = open(path, encoding='utf8', newline='').read()
nl = '\r\n' if '\r\n' in s else '\n'
T = '\t\t'


def diel(n, kind, plies):
    first = plies[0]
    txt = '%s\t(layer "dielectric %d"%s%s\t\t(type "%s")%s' % (T, n, nl, T, kind, nl)
    txt += '%s\t\t(thickness %s)%s%s\t\t(material "%s")%s%s\t\t(epsilon_r %s)%s%s\t\t(loss_tangent 0.02)%s' % (
        T, first[0], nl, T, first[1], nl, T, first[2], nl, T, nl)
    for th, mat, er in plies[1:]:
        txt += '%s\t\taddsublayer%s%s\t\t(thickness %s)%s%s\t\t(material "%s")%s%s\t\t(epsilon_r %s)%s%s\t\t(loss_tangent 0.02)%s' % (
            T, nl, T, th, nl, T, mat, nl, T, er, nl, T, nl)
    txt += '%s\t)%s' % (T, nl)
    return txt


def cu(name, th):
    return '%s\t(layer "%s"%s%s\t\t(type "copper")%s%s\t\t(thickness %s)%s%s\t)%s' % (T, name, nl, T, nl, T, th, nl, T, nl)


def simple(name, typ, th=None):
    t = '%s\t(layer "%s"%s%s\t\t(type "%s")%s' % (T, name, nl, T, typ, nl)
    if th:
        t += '%s\t\t(thickness %s)%s' % (T, th, nl)
    return t + '%s\t)%s' % (T, nl)


P = ('0.109', '2116 NP-155F', '4.16')
CORE = [('0.25', 'Core NP-155F', '4.23')]
body = (simple('F.SilkS', 'Top Silk Screen') + simple('F.Paste', 'Top Solder Paste') +
        simple('F.Mask', 'Top Solder Mask', '0.01') +
        cu('F.Cu', '0.035') + diel(1, 'prepreg', [P]) + cu('In1.Cu', '0.03') + diel(2, 'core', CORE) +
        cu('In2.Cu', '0.03') + diel(3, 'prepreg', [P, P]) + cu('In3.Cu', '0.03') + diel(4, 'core', CORE) +
        cu('In4.Cu', '0.03') + diel(5, 'prepreg', [P, P]) + cu('In5.Cu', '0.03') + diel(6, 'core', CORE) +
        cu('In6.Cu', '0.03') + diel(7, 'prepreg', [P]) + cu('B.Cu', '0.035') +
        simple('B.Mask', 'Bottom Solder Mask', '0.01') + simple('B.Paste', 'Bottom Solder Paste') +
        simple('B.SilkS', 'Bottom Silk Screen') +
        '%s\t(copper_finish "None")%s%s\t(dielectric_constraints no)%s' % (T, nl, T, nl))
block = '%s(stackup%s%s%s)%s' % (T, nl, body, T, nl)

s = re.sub(r'\t\t\(stackup\r?\n.*?\r?\n\t\t\)\r?\n', '', s, flags=re.S)       # replace any earlier stackup
i = s.index('\t(setup')
j = s.index(nl, i) + len(nl)
s = s[:j] + block + s[j:]
s = re.sub(r'(\(general\s*\r?\n\s*\(thickness )[0-9.]+\)', r'\g<1>1.654)', s, count=1)
open(path, 'w', encoding='utf8', newline='').write(s)
print('stackup written to', path)
